#cloud-config

rancher:
  network:
    interfaces:
	  eth*:
	    dhcp: true
	  dns:
	    nameservers:
		  - 8.8.8.8
		  - 8.8.4.4
hostname: spacemonkey
ssh_authorized_keys:
 - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEApa1e6Gy6NdsuTZWw9VZSjPd3rO4Q/QUAK84GufVHkXjKKQehVfmcbELJWBbHKR06ABq/ZxBXGIsw+ga9PBdMfAxz8uIwjkD4pt2OpY8LBtKXXLVzh4T0HlUqQNMl3/5k7qipnd//mt5F0Y/ku1Vc87imZb4oZKb0fU34fpUNVq6o2WXjaF7pXZhO3ClVH2matJtX5Yacn6vLctbVwVtKKWNCGLsDvO7usdF1IlBoniCF0Of5uK5ZByUaGt6P9UyJ90/tqtwaCa/e4ge5JERaA8HP84TKd1aFn3LNGGU/Y0w4/CQ+0xWSQANcN8Xkecw4oLGW36noQbjmInX7kPTsPw== rsa-key-20151027
